### ISSUE TITLE
fix indentation according to the rules of whatever they gave to us

### ISSUE THREAD

**Issue by rover33** [jasonbrettcox/project1#1]
function init() {
                uiComplete.hide();
                uiCards.hide();
                playGame = false;
                uiPlay.click(function(e){
                    e.preventDefault();
                    uiIntro.hide();
                    startGame();
                });

                uiReset.click(function(e){
                e.preventDefault();
                uiComplete.hide();
                reStartGame();
            
            });
}

**Comment by rover33** [comment]
on the index.html you have some matching  </div>        </div> on the same line

**Comment by jasonbrettcox** [comment]
Thank you, I have cleaned this up
